#!/usr/bin/env bash

# Update package list and install Nginx
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y
sudo apt-get install nginx -y

# Allowing Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Creating new index
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Create custom 404 page
sudo mkdir -p /var/www/ajayivii.tech/html
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/ajayivii.tech/html/custom_404.html > /dev/null

# Setting up /redirect_me to google
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.google.com/;\n\t}' /etc/nginx/sites-available/default

# Set up a 404 page
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\tinternal;\n\t\troot /var/www/ajayivii.tech/html;\n\t}' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx start
sudo nginx -s reload

echo -e "\nCompleted.\n"

