#!/usr/bin/env bash
# This script displays different messages based on loop iteration

# Initialize a counter
counter=1

# Loop from 1 to 20
while [ $counter -le 20 ]; do
    # Check for special cases
    case $counter in
        4)
            echo "$counter and then bad luck from China"
            ;;
        9)
            echo "$counter and then bad luck from Japan"
            ;;
        17)
            echo "$counter and then bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    ((counter++))
done

