#!/usr/bin/env bash
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
service nginx stop
service nginx start
