#!/usr/bin/env bash

# Script to create an RSA key pair with specific requirements

# Define variables for key name, bits, and passphrase
KEY_NAME="school"
BITS="4096"
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $BITS -f $KEY_NAME -N $PASSPHRASE
